version: '3'
services:
  python3:
    restart: always
    build: 
      context: ./docker
      dockerfile: python/Dockerfile
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./work:/root/work
